Repository odders17/Football-info-MERN-app, pull requests merged in 2022-02, with the labels that each got.

#19 renamed to client folder
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/Navbar.js
  client/src/components/SignupForm.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: documentation, enhancement

#27 Resolve confilct
  client/package-lock.json
  client/package.json
  package-lock.json
  server/package-lock.json
  server/package.json
Labels: bug

#28 moved API key
  client/src/utils/searchreq.js
Labels: bug

#33 Display team stats
  client/package-lock.json
  client/src/components/Team.js
  client/src/utils/searchreq.js
  package-lock.json
  server/package-lock.json
Labels: documentation

#35 Display team stats
  assets/pitch.jpg
  client/src/components/Team.js
  client/src/images/pitch.jpg
  client/tailwind.config.js
Labels: enhancement

#37 #29privateapi
  client/package-lock.json
  client/src/App.js
  client/src/components/Player.js
  client/src/components/Team.js
  client/src/components/Teams.js
  client/src/utils/queries.js
  client/src/utils/searchreq.js
  package-lock.json
  server/package-lock.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#41 Made some tweeks to table styling
  client/src/components/Teams.js
Labels: enhancement

#42 Link teams to player
  client/src/App.js
  client/src/components/Player.js
  client/src/components/Team.js
Labels: enhancement

#44 make changes to the main page style
  client/src/App.js
  client/src/components/Navbar.js
  client/src/components/Player.js
  client/src/components/PlayerInfo.js
  client/src/components/Team.js
  client/src/components/Teams copy.js
  client/src/components/Teams.js
  client/src/components/team.css
Labels: enhancement

#45 Added styling to data page and changed link- table
  client/src/components/Player.js
  client/src/components/PlayerInfo.js
  client/src/components/Team.js
  client/src/components/Teams.js
  client/src/components/team.css
Labels: enhancement

#46 Added readme
  README.md
  assets/Football-info.png
Labels: documentation

#50 Uibranch
  client/src/components/Team.js
Labels: enhancement

#52 Added image
  client/src/components/Player.js
  client/src/components/PlayerInfo.js
  client/src/components/Teams copy.js
  client/src/images/roy.jpg
Labels: enhancement
